# docker-compose.yml
services:
  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_REGION:  ${AWS_S3_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo
    restart: on-failure
    networks:
      - app-network
  
  mongo:
    image: mongo:8
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network
    restart: on-failure
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge