# docker-compose.yml
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo
    restart: always
    networks:
      - app-network
  
  mongo:
    image: mongo:8
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network
    restart: on-failure
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge